
//input ports
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point mem_req_ready mem_req_ready -type PI PI
add mapped point mem_req_data_ready mem_req_data_ready -type PI PI
add mapped point mem_resp_valid mem_resp_valid -type PI PI
add mapped point mem_resp_tag[4] mem_resp_tag[4] -type PI PI
add mapped point mem_resp_tag[3] mem_resp_tag[3] -type PI PI
add mapped point mem_resp_tag[2] mem_resp_tag[2] -type PI PI
add mapped point mem_resp_tag[1] mem_resp_tag[1] -type PI PI
add mapped point mem_resp_tag[0] mem_resp_tag[0] -type PI PI
add mapped point mem_resp_data[127] mem_resp_data[127] -type PI PI
add mapped point mem_resp_data[126] mem_resp_data[126] -type PI PI
add mapped point mem_resp_data[125] mem_resp_data[125] -type PI PI
add mapped point mem_resp_data[124] mem_resp_data[124] -type PI PI
add mapped point mem_resp_data[123] mem_resp_data[123] -type PI PI
add mapped point mem_resp_data[122] mem_resp_data[122] -type PI PI
add mapped point mem_resp_data[121] mem_resp_data[121] -type PI PI
add mapped point mem_resp_data[120] mem_resp_data[120] -type PI PI
add mapped point mem_resp_data[119] mem_resp_data[119] -type PI PI
add mapped point mem_resp_data[118] mem_resp_data[118] -type PI PI
add mapped point mem_resp_data[117] mem_resp_data[117] -type PI PI
add mapped point mem_resp_data[116] mem_resp_data[116] -type PI PI
add mapped point mem_resp_data[115] mem_resp_data[115] -type PI PI
add mapped point mem_resp_data[114] mem_resp_data[114] -type PI PI
add mapped point mem_resp_data[113] mem_resp_data[113] -type PI PI
add mapped point mem_resp_data[112] mem_resp_data[112] -type PI PI
add mapped point mem_resp_data[111] mem_resp_data[111] -type PI PI
add mapped point mem_resp_data[110] mem_resp_data[110] -type PI PI
add mapped point mem_resp_data[109] mem_resp_data[109] -type PI PI
add mapped point mem_resp_data[108] mem_resp_data[108] -type PI PI
add mapped point mem_resp_data[107] mem_resp_data[107] -type PI PI
add mapped point mem_resp_data[106] mem_resp_data[106] -type PI PI
add mapped point mem_resp_data[105] mem_resp_data[105] -type PI PI
add mapped point mem_resp_data[104] mem_resp_data[104] -type PI PI
add mapped point mem_resp_data[103] mem_resp_data[103] -type PI PI
add mapped point mem_resp_data[102] mem_resp_data[102] -type PI PI
add mapped point mem_resp_data[101] mem_resp_data[101] -type PI PI
add mapped point mem_resp_data[100] mem_resp_data[100] -type PI PI
add mapped point mem_resp_data[99] mem_resp_data[99] -type PI PI
add mapped point mem_resp_data[98] mem_resp_data[98] -type PI PI
add mapped point mem_resp_data[97] mem_resp_data[97] -type PI PI
add mapped point mem_resp_data[96] mem_resp_data[96] -type PI PI
add mapped point mem_resp_data[95] mem_resp_data[95] -type PI PI
add mapped point mem_resp_data[94] mem_resp_data[94] -type PI PI
add mapped point mem_resp_data[93] mem_resp_data[93] -type PI PI
add mapped point mem_resp_data[92] mem_resp_data[92] -type PI PI
add mapped point mem_resp_data[91] mem_resp_data[91] -type PI PI
add mapped point mem_resp_data[90] mem_resp_data[90] -type PI PI
add mapped point mem_resp_data[89] mem_resp_data[89] -type PI PI
add mapped point mem_resp_data[88] mem_resp_data[88] -type PI PI
add mapped point mem_resp_data[87] mem_resp_data[87] -type PI PI
add mapped point mem_resp_data[86] mem_resp_data[86] -type PI PI
add mapped point mem_resp_data[85] mem_resp_data[85] -type PI PI
add mapped point mem_resp_data[84] mem_resp_data[84] -type PI PI
add mapped point mem_resp_data[83] mem_resp_data[83] -type PI PI
add mapped point mem_resp_data[82] mem_resp_data[82] -type PI PI
add mapped point mem_resp_data[81] mem_resp_data[81] -type PI PI
add mapped point mem_resp_data[80] mem_resp_data[80] -type PI PI
add mapped point mem_resp_data[79] mem_resp_data[79] -type PI PI
add mapped point mem_resp_data[78] mem_resp_data[78] -type PI PI
add mapped point mem_resp_data[77] mem_resp_data[77] -type PI PI
add mapped point mem_resp_data[76] mem_resp_data[76] -type PI PI
add mapped point mem_resp_data[75] mem_resp_data[75] -type PI PI
add mapped point mem_resp_data[74] mem_resp_data[74] -type PI PI
add mapped point mem_resp_data[73] mem_resp_data[73] -type PI PI
add mapped point mem_resp_data[72] mem_resp_data[72] -type PI PI
add mapped point mem_resp_data[71] mem_resp_data[71] -type PI PI
add mapped point mem_resp_data[70] mem_resp_data[70] -type PI PI
add mapped point mem_resp_data[69] mem_resp_data[69] -type PI PI
add mapped point mem_resp_data[68] mem_resp_data[68] -type PI PI
add mapped point mem_resp_data[67] mem_resp_data[67] -type PI PI
add mapped point mem_resp_data[66] mem_resp_data[66] -type PI PI
add mapped point mem_resp_data[65] mem_resp_data[65] -type PI PI
add mapped point mem_resp_data[64] mem_resp_data[64] -type PI PI
add mapped point mem_resp_data[63] mem_resp_data[63] -type PI PI
add mapped point mem_resp_data[62] mem_resp_data[62] -type PI PI
add mapped point mem_resp_data[61] mem_resp_data[61] -type PI PI
add mapped point mem_resp_data[60] mem_resp_data[60] -type PI PI
add mapped point mem_resp_data[59] mem_resp_data[59] -type PI PI
add mapped point mem_resp_data[58] mem_resp_data[58] -type PI PI
add mapped point mem_resp_data[57] mem_resp_data[57] -type PI PI
add mapped point mem_resp_data[56] mem_resp_data[56] -type PI PI
add mapped point mem_resp_data[55] mem_resp_data[55] -type PI PI
add mapped point mem_resp_data[54] mem_resp_data[54] -type PI PI
add mapped point mem_resp_data[53] mem_resp_data[53] -type PI PI
add mapped point mem_resp_data[52] mem_resp_data[52] -type PI PI
add mapped point mem_resp_data[51] mem_resp_data[51] -type PI PI
add mapped point mem_resp_data[50] mem_resp_data[50] -type PI PI
add mapped point mem_resp_data[49] mem_resp_data[49] -type PI PI
add mapped point mem_resp_data[48] mem_resp_data[48] -type PI PI
add mapped point mem_resp_data[47] mem_resp_data[47] -type PI PI
add mapped point mem_resp_data[46] mem_resp_data[46] -type PI PI
add mapped point mem_resp_data[45] mem_resp_data[45] -type PI PI
add mapped point mem_resp_data[44] mem_resp_data[44] -type PI PI
add mapped point mem_resp_data[43] mem_resp_data[43] -type PI PI
add mapped point mem_resp_data[42] mem_resp_data[42] -type PI PI
add mapped point mem_resp_data[41] mem_resp_data[41] -type PI PI
add mapped point mem_resp_data[40] mem_resp_data[40] -type PI PI
add mapped point mem_resp_data[39] mem_resp_data[39] -type PI PI
add mapped point mem_resp_data[38] mem_resp_data[38] -type PI PI
add mapped point mem_resp_data[37] mem_resp_data[37] -type PI PI
add mapped point mem_resp_data[36] mem_resp_data[36] -type PI PI
add mapped point mem_resp_data[35] mem_resp_data[35] -type PI PI
add mapped point mem_resp_data[34] mem_resp_data[34] -type PI PI
add mapped point mem_resp_data[33] mem_resp_data[33] -type PI PI
add mapped point mem_resp_data[32] mem_resp_data[32] -type PI PI
add mapped point mem_resp_data[31] mem_resp_data[31] -type PI PI
add mapped point mem_resp_data[30] mem_resp_data[30] -type PI PI
add mapped point mem_resp_data[29] mem_resp_data[29] -type PI PI
add mapped point mem_resp_data[28] mem_resp_data[28] -type PI PI
add mapped point mem_resp_data[27] mem_resp_data[27] -type PI PI
add mapped point mem_resp_data[26] mem_resp_data[26] -type PI PI
add mapped point mem_resp_data[25] mem_resp_data[25] -type PI PI
add mapped point mem_resp_data[24] mem_resp_data[24] -type PI PI
add mapped point mem_resp_data[23] mem_resp_data[23] -type PI PI
add mapped point mem_resp_data[22] mem_resp_data[22] -type PI PI
add mapped point mem_resp_data[21] mem_resp_data[21] -type PI PI
add mapped point mem_resp_data[20] mem_resp_data[20] -type PI PI
add mapped point mem_resp_data[19] mem_resp_data[19] -type PI PI
add mapped point mem_resp_data[18] mem_resp_data[18] -type PI PI
add mapped point mem_resp_data[17] mem_resp_data[17] -type PI PI
add mapped point mem_resp_data[16] mem_resp_data[16] -type PI PI
add mapped point mem_resp_data[15] mem_resp_data[15] -type PI PI
add mapped point mem_resp_data[14] mem_resp_data[14] -type PI PI
add mapped point mem_resp_data[13] mem_resp_data[13] -type PI PI
add mapped point mem_resp_data[12] mem_resp_data[12] -type PI PI
add mapped point mem_resp_data[11] mem_resp_data[11] -type PI PI
add mapped point mem_resp_data[10] mem_resp_data[10] -type PI PI
add mapped point mem_resp_data[9] mem_resp_data[9] -type PI PI
add mapped point mem_resp_data[8] mem_resp_data[8] -type PI PI
add mapped point mem_resp_data[7] mem_resp_data[7] -type PI PI
add mapped point mem_resp_data[6] mem_resp_data[6] -type PI PI
add mapped point mem_resp_data[5] mem_resp_data[5] -type PI PI
add mapped point mem_resp_data[4] mem_resp_data[4] -type PI PI
add mapped point mem_resp_data[3] mem_resp_data[3] -type PI PI
add mapped point mem_resp_data[2] mem_resp_data[2] -type PI PI
add mapped point mem_resp_data[1] mem_resp_data[1] -type PI PI
add mapped point mem_resp_data[0] mem_resp_data[0] -type PI PI

//output ports
add mapped point mem_req_valid mem_req_valid -type PO PO
add mapped point mem_req_rw mem_req_rw -type PO PO
add mapped point mem_req_addr[27] mem_req_addr[27] -type PO PO
add mapped point mem_req_addr[26] mem_req_addr[26] -type PO PO
add mapped point mem_req_addr[25] mem_req_addr[25] -type PO PO
add mapped point mem_req_addr[24] mem_req_addr[24] -type PO PO
add mapped point mem_req_addr[23] mem_req_addr[23] -type PO PO
add mapped point mem_req_addr[22] mem_req_addr[22] -type PO PO
add mapped point mem_req_addr[21] mem_req_addr[21] -type PO PO
add mapped point mem_req_addr[20] mem_req_addr[20] -type PO PO
add mapped point mem_req_addr[19] mem_req_addr[19] -type PO PO
add mapped point mem_req_addr[18] mem_req_addr[18] -type PO PO
add mapped point mem_req_addr[17] mem_req_addr[17] -type PO PO
add mapped point mem_req_addr[16] mem_req_addr[16] -type PO PO
add mapped point mem_req_addr[15] mem_req_addr[15] -type PO PO
add mapped point mem_req_addr[14] mem_req_addr[14] -type PO PO
add mapped point mem_req_addr[13] mem_req_addr[13] -type PO PO
add mapped point mem_req_addr[12] mem_req_addr[12] -type PO PO
add mapped point mem_req_addr[11] mem_req_addr[11] -type PO PO
add mapped point mem_req_addr[10] mem_req_addr[10] -type PO PO
add mapped point mem_req_addr[9] mem_req_addr[9] -type PO PO
add mapped point mem_req_addr[8] mem_req_addr[8] -type PO PO
add mapped point mem_req_addr[7] mem_req_addr[7] -type PO PO
add mapped point mem_req_addr[6] mem_req_addr[6] -type PO PO
add mapped point mem_req_addr[5] mem_req_addr[5] -type PO PO
add mapped point mem_req_addr[4] mem_req_addr[4] -type PO PO
add mapped point mem_req_addr[3] mem_req_addr[3] -type PO PO
add mapped point mem_req_addr[2] mem_req_addr[2] -type PO PO
add mapped point mem_req_addr[1] mem_req_addr[1] -type PO PO
add mapped point mem_req_addr[0] mem_req_addr[0] -type PO PO
add mapped point mem_req_tag[4] mem_req_tag[4] -type PO PO
add mapped point mem_req_tag[3] mem_req_tag[3] -type PO PO
add mapped point mem_req_tag[2] mem_req_tag[2] -type PO PO
add mapped point mem_req_tag[1] mem_req_tag[1] -type PO PO
add mapped point mem_req_tag[0] mem_req_tag[0] -type PO PO
add mapped point mem_req_data_valid mem_req_data_valid -type PO PO
add mapped point mem_req_data_bits[127] mem_req_data_bits[127] -type PO PO
add mapped point mem_req_data_bits[126] mem_req_data_bits[126] -type PO PO
add mapped point mem_req_data_bits[125] mem_req_data_bits[125] -type PO PO
add mapped point mem_req_data_bits[124] mem_req_data_bits[124] -type PO PO
add mapped point mem_req_data_bits[123] mem_req_data_bits[123] -type PO PO
add mapped point mem_req_data_bits[122] mem_req_data_bits[122] -type PO PO
add mapped point mem_req_data_bits[121] mem_req_data_bits[121] -type PO PO
add mapped point mem_req_data_bits[120] mem_req_data_bits[120] -type PO PO
add mapped point mem_req_data_bits[119] mem_req_data_bits[119] -type PO PO
add mapped point mem_req_data_bits[118] mem_req_data_bits[118] -type PO PO
add mapped point mem_req_data_bits[117] mem_req_data_bits[117] -type PO PO
add mapped point mem_req_data_bits[116] mem_req_data_bits[116] -type PO PO
add mapped point mem_req_data_bits[115] mem_req_data_bits[115] -type PO PO
add mapped point mem_req_data_bits[114] mem_req_data_bits[114] -type PO PO
add mapped point mem_req_data_bits[113] mem_req_data_bits[113] -type PO PO
add mapped point mem_req_data_bits[112] mem_req_data_bits[112] -type PO PO
add mapped point mem_req_data_bits[111] mem_req_data_bits[111] -type PO PO
add mapped point mem_req_data_bits[110] mem_req_data_bits[110] -type PO PO
add mapped point mem_req_data_bits[109] mem_req_data_bits[109] -type PO PO
add mapped point mem_req_data_bits[108] mem_req_data_bits[108] -type PO PO
add mapped point mem_req_data_bits[107] mem_req_data_bits[107] -type PO PO
add mapped point mem_req_data_bits[106] mem_req_data_bits[106] -type PO PO
add mapped point mem_req_data_bits[105] mem_req_data_bits[105] -type PO PO
add mapped point mem_req_data_bits[104] mem_req_data_bits[104] -type PO PO
add mapped point mem_req_data_bits[103] mem_req_data_bits[103] -type PO PO
add mapped point mem_req_data_bits[102] mem_req_data_bits[102] -type PO PO
add mapped point mem_req_data_bits[101] mem_req_data_bits[101] -type PO PO
add mapped point mem_req_data_bits[100] mem_req_data_bits[100] -type PO PO
add mapped point mem_req_data_bits[99] mem_req_data_bits[99] -type PO PO
add mapped point mem_req_data_bits[98] mem_req_data_bits[98] -type PO PO
add mapped point mem_req_data_bits[97] mem_req_data_bits[97] -type PO PO
add mapped point mem_req_data_bits[96] mem_req_data_bits[96] -type PO PO
add mapped point mem_req_data_bits[95] mem_req_data_bits[95] -type PO PO
add mapped point mem_req_data_bits[94] mem_req_data_bits[94] -type PO PO
add mapped point mem_req_data_bits[93] mem_req_data_bits[93] -type PO PO
add mapped point mem_req_data_bits[92] mem_req_data_bits[92] -type PO PO
add mapped point mem_req_data_bits[91] mem_req_data_bits[91] -type PO PO
add mapped point mem_req_data_bits[90] mem_req_data_bits[90] -type PO PO
add mapped point mem_req_data_bits[89] mem_req_data_bits[89] -type PO PO
add mapped point mem_req_data_bits[88] mem_req_data_bits[88] -type PO PO
add mapped point mem_req_data_bits[87] mem_req_data_bits[87] -type PO PO
add mapped point mem_req_data_bits[86] mem_req_data_bits[86] -type PO PO
add mapped point mem_req_data_bits[85] mem_req_data_bits[85] -type PO PO
add mapped point mem_req_data_bits[84] mem_req_data_bits[84] -type PO PO
add mapped point mem_req_data_bits[83] mem_req_data_bits[83] -type PO PO
add mapped point mem_req_data_bits[82] mem_req_data_bits[82] -type PO PO
add mapped point mem_req_data_bits[81] mem_req_data_bits[81] -type PO PO
add mapped point mem_req_data_bits[80] mem_req_data_bits[80] -type PO PO
add mapped point mem_req_data_bits[79] mem_req_data_bits[79] -type PO PO
add mapped point mem_req_data_bits[78] mem_req_data_bits[78] -type PO PO
add mapped point mem_req_data_bits[77] mem_req_data_bits[77] -type PO PO
add mapped point mem_req_data_bits[76] mem_req_data_bits[76] -type PO PO
add mapped point mem_req_data_bits[75] mem_req_data_bits[75] -type PO PO
add mapped point mem_req_data_bits[74] mem_req_data_bits[74] -type PO PO
add mapped point mem_req_data_bits[73] mem_req_data_bits[73] -type PO PO
add mapped point mem_req_data_bits[72] mem_req_data_bits[72] -type PO PO
add mapped point mem_req_data_bits[71] mem_req_data_bits[71] -type PO PO
add mapped point mem_req_data_bits[70] mem_req_data_bits[70] -type PO PO
add mapped point mem_req_data_bits[69] mem_req_data_bits[69] -type PO PO
add mapped point mem_req_data_bits[68] mem_req_data_bits[68] -type PO PO
add mapped point mem_req_data_bits[67] mem_req_data_bits[67] -type PO PO
add mapped point mem_req_data_bits[66] mem_req_data_bits[66] -type PO PO
add mapped point mem_req_data_bits[65] mem_req_data_bits[65] -type PO PO
add mapped point mem_req_data_bits[64] mem_req_data_bits[64] -type PO PO
add mapped point mem_req_data_bits[63] mem_req_data_bits[63] -type PO PO
add mapped point mem_req_data_bits[62] mem_req_data_bits[62] -type PO PO
add mapped point mem_req_data_bits[61] mem_req_data_bits[61] -type PO PO
add mapped point mem_req_data_bits[60] mem_req_data_bits[60] -type PO PO
add mapped point mem_req_data_bits[59] mem_req_data_bits[59] -type PO PO
add mapped point mem_req_data_bits[58] mem_req_data_bits[58] -type PO PO
add mapped point mem_req_data_bits[57] mem_req_data_bits[57] -type PO PO
add mapped point mem_req_data_bits[56] mem_req_data_bits[56] -type PO PO
add mapped point mem_req_data_bits[55] mem_req_data_bits[55] -type PO PO
add mapped point mem_req_data_bits[54] mem_req_data_bits[54] -type PO PO
add mapped point mem_req_data_bits[53] mem_req_data_bits[53] -type PO PO
add mapped point mem_req_data_bits[52] mem_req_data_bits[52] -type PO PO
add mapped point mem_req_data_bits[51] mem_req_data_bits[51] -type PO PO
add mapped point mem_req_data_bits[50] mem_req_data_bits[50] -type PO PO
add mapped point mem_req_data_bits[49] mem_req_data_bits[49] -type PO PO
add mapped point mem_req_data_bits[48] mem_req_data_bits[48] -type PO PO
add mapped point mem_req_data_bits[47] mem_req_data_bits[47] -type PO PO
add mapped point mem_req_data_bits[46] mem_req_data_bits[46] -type PO PO
add mapped point mem_req_data_bits[45] mem_req_data_bits[45] -type PO PO
add mapped point mem_req_data_bits[44] mem_req_data_bits[44] -type PO PO
add mapped point mem_req_data_bits[43] mem_req_data_bits[43] -type PO PO
add mapped point mem_req_data_bits[42] mem_req_data_bits[42] -type PO PO
add mapped point mem_req_data_bits[41] mem_req_data_bits[41] -type PO PO
add mapped point mem_req_data_bits[40] mem_req_data_bits[40] -type PO PO
add mapped point mem_req_data_bits[39] mem_req_data_bits[39] -type PO PO
add mapped point mem_req_data_bits[38] mem_req_data_bits[38] -type PO PO
add mapped point mem_req_data_bits[37] mem_req_data_bits[37] -type PO PO
add mapped point mem_req_data_bits[36] mem_req_data_bits[36] -type PO PO
add mapped point mem_req_data_bits[35] mem_req_data_bits[35] -type PO PO
add mapped point mem_req_data_bits[34] mem_req_data_bits[34] -type PO PO
add mapped point mem_req_data_bits[33] mem_req_data_bits[33] -type PO PO
add mapped point mem_req_data_bits[32] mem_req_data_bits[32] -type PO PO
add mapped point mem_req_data_bits[31] mem_req_data_bits[31] -type PO PO
add mapped point mem_req_data_bits[30] mem_req_data_bits[30] -type PO PO
add mapped point mem_req_data_bits[29] mem_req_data_bits[29] -type PO PO
add mapped point mem_req_data_bits[28] mem_req_data_bits[28] -type PO PO
add mapped point mem_req_data_bits[27] mem_req_data_bits[27] -type PO PO
add mapped point mem_req_data_bits[26] mem_req_data_bits[26] -type PO PO
add mapped point mem_req_data_bits[25] mem_req_data_bits[25] -type PO PO
add mapped point mem_req_data_bits[24] mem_req_data_bits[24] -type PO PO
add mapped point mem_req_data_bits[23] mem_req_data_bits[23] -type PO PO
add mapped point mem_req_data_bits[22] mem_req_data_bits[22] -type PO PO
add mapped point mem_req_data_bits[21] mem_req_data_bits[21] -type PO PO
add mapped point mem_req_data_bits[20] mem_req_data_bits[20] -type PO PO
add mapped point mem_req_data_bits[19] mem_req_data_bits[19] -type PO PO
add mapped point mem_req_data_bits[18] mem_req_data_bits[18] -type PO PO
add mapped point mem_req_data_bits[17] mem_req_data_bits[17] -type PO PO
add mapped point mem_req_data_bits[16] mem_req_data_bits[16] -type PO PO
add mapped point mem_req_data_bits[15] mem_req_data_bits[15] -type PO PO
add mapped point mem_req_data_bits[14] mem_req_data_bits[14] -type PO PO
add mapped point mem_req_data_bits[13] mem_req_data_bits[13] -type PO PO
add mapped point mem_req_data_bits[12] mem_req_data_bits[12] -type PO PO
add mapped point mem_req_data_bits[11] mem_req_data_bits[11] -type PO PO
add mapped point mem_req_data_bits[10] mem_req_data_bits[10] -type PO PO
add mapped point mem_req_data_bits[9] mem_req_data_bits[9] -type PO PO
add mapped point mem_req_data_bits[8] mem_req_data_bits[8] -type PO PO
add mapped point mem_req_data_bits[7] mem_req_data_bits[7] -type PO PO
add mapped point mem_req_data_bits[6] mem_req_data_bits[6] -type PO PO
add mapped point mem_req_data_bits[5] mem_req_data_bits[5] -type PO PO
add mapped point mem_req_data_bits[4] mem_req_data_bits[4] -type PO PO
add mapped point mem_req_data_bits[3] mem_req_data_bits[3] -type PO PO
add mapped point mem_req_data_bits[2] mem_req_data_bits[2] -type PO PO
add mapped point mem_req_data_bits[1] mem_req_data_bits[1] -type PO PO
add mapped point mem_req_data_bits[0] mem_req_data_bits[0] -type PO PO
add mapped point mem_req_data_mask[15] mem_req_data_mask[15] -type PO PO
add mapped point mem_req_data_mask[14] mem_req_data_mask[14] -type PO PO
add mapped point mem_req_data_mask[13] mem_req_data_mask[13] -type PO PO
add mapped point mem_req_data_mask[12] mem_req_data_mask[12] -type PO PO
add mapped point mem_req_data_mask[11] mem_req_data_mask[11] -type PO PO
add mapped point mem_req_data_mask[10] mem_req_data_mask[10] -type PO PO
add mapped point mem_req_data_mask[9] mem_req_data_mask[9] -type PO PO
add mapped point mem_req_data_mask[8] mem_req_data_mask[8] -type PO PO
add mapped point mem_req_data_mask[7] mem_req_data_mask[7] -type PO PO
add mapped point mem_req_data_mask[6] mem_req_data_mask[6] -type PO PO
add mapped point mem_req_data_mask[5] mem_req_data_mask[5] -type PO PO
add mapped point mem_req_data_mask[4] mem_req_data_mask[4] -type PO PO
add mapped point mem_req_data_mask[3] mem_req_data_mask[3] -type PO PO
add mapped point mem_req_data_mask[2] mem_req_data_mask[2] -type PO PO
add mapped point mem_req_data_mask[1] mem_req_data_mask[1] -type PO PO
add mapped point mem_req_data_mask[0] mem_req_data_mask[0] -type PO PO
add mapped point csr[31] csr[31] -type PO PO
add mapped point csr[30] csr[30] -type PO PO
add mapped point csr[29] csr[29] -type PO PO
add mapped point csr[28] csr[28] -type PO PO
add mapped point csr[27] csr[27] -type PO PO
add mapped point csr[26] csr[26] -type PO PO
add mapped point csr[25] csr[25] -type PO PO
add mapped point csr[24] csr[24] -type PO PO
add mapped point csr[23] csr[23] -type PO PO
add mapped point csr[22] csr[22] -type PO PO
add mapped point csr[21] csr[21] -type PO PO
add mapped point csr[20] csr[20] -type PO PO
add mapped point csr[19] csr[19] -type PO PO
add mapped point csr[18] csr[18] -type PO PO
add mapped point csr[17] csr[17] -type PO PO
add mapped point csr[16] csr[16] -type PO PO
add mapped point csr[15] csr[15] -type PO PO
add mapped point csr[14] csr[14] -type PO PO
add mapped point csr[13] csr[13] -type PO PO
add mapped point csr[12] csr[12] -type PO PO
add mapped point csr[11] csr[11] -type PO PO
add mapped point csr[10] csr[10] -type PO PO
add mapped point csr[9] csr[9] -type PO PO
add mapped point csr[8] csr[8] -type PO PO
add mapped point csr[7] csr[7] -type PO PO
add mapped point csr[6] csr[6] -type PO PO
add mapped point csr[5] csr[5] -type PO PO
add mapped point csr[4] csr[4] -type PO PO
add mapped point csr[3] csr[3] -type PO PO
add mapped point csr[2] csr[2] -type PO PO
add mapped point csr[1] csr[1] -type PO PO
add mapped point csr[0] csr[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[21]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[21]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[20]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[20]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[22]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[22]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[18]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[18]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[19]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[19]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[17]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[17]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[16]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[16]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[14]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[14]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[15]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[15]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[13]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[13]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[12]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[12]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[11]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[11]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[10]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[10]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[9]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[9]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[8]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[8]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[5]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[5]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[24]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[24]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[6]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[6]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[4]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[4]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[2]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[2]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[3]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[3]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[1]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[1]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[0]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[0]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[23]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[23]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[31]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[31]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[29]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[29]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[30]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[30]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[28]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[28]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[27]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[27]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[26]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[26]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[25]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[25]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/data_out_B[7]/q cpu/DATA_DX/DATA_REGFILE/data_out_B_reg[7]/Q -type DLAT DLAT
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][16]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][16]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][1]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][1]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][3]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][3]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][4]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][4]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][2]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][2]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][6]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][6]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][8]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][8]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][7]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][7]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][9]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][9]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][10]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][10]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][11]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][11]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][12]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][12]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][13]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][13]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][14]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][14]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][15]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][15]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][0]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][0]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][5]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][5]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][18]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][18]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][19]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][19]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][21]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][21]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][20]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][20]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][22]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][22]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][23]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][23]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][24]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][24]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][25]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][25]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][26]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][26]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][27]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][27]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][28]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][28]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][29]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][29]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][30]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][30]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][31]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][31]/QN -type DFF DFF
add mapped point cpu/DATA_DX/DATA_REGFILE/mem[0][17]/q cpu/DATA_DX/DATA_REGFILE/mem_reg[0][17]/QN -type DFF DFF
add mapped point cpu/PC_GEN/next_pc[13]/q cpu/PC_GEN/next_pc_reg[13]/QN -type DFF DFF
add mapped point mem/dcache/memory_rw_ctr[1]/q mem/dcache/memory_rw_ctr_reg[1]296/QN -type DFF DFF
add mapped point mem/dcache/memory_rw_ctr[0]/q mem/dcache/memory_rw_ctr_reg[0]295/QN -type DFF DFF
add mapped point mem/dcache/state[0]/q mem/dcache/state_reg[0]/QN -type DFF DFF
add mapped point mem/dcache/state[1]/q mem/dcache/state_reg[1]/QN -type DFF DFF
add mapped point mem/dcache/state[2]/q mem/dcache/state_reg[2]/QN -type DFF DFF
add mapped point mem/dcache/cpu_req_ready/q mem/dcache/cpu_req_ready_reg304/Q -type DLAT DLAT
add mapped point mem/dcache/dirty_bits[0]/q mem/dcache/dirty_bits_reg[0]308/Q -type DLAT DLAT
add mapped point mem/dcache/nextstate[0]/q mem/dcache/nextstate_reg[0]/Q -type DLAT DLAT
add mapped point mem/dcache/sram_mem_web_0/q mem/dcache/sram_mem_web_0_reg/Q -type DLAT DLAT
add mapped point mem/dcache/mem_req_data_valid/q mem/dcache/mem_req_data_valid_reg/Q -type DLAT DLAT
add mapped point mem/dcache/sram_mem_web_1/q mem/dcache/sram_mem_web_1_reg/Q -type DLAT DLAT
add mapped point mem/dcache/nextstate[2]/q mem/dcache/nextstate_reg[2]/Q -type DLAT DLAT
add mapped point mem/dcache/nextstate[1]/q mem/dcache/nextstate_reg[1]/Q -type DLAT DLAT
add mapped point mem/dcache/tag_cpu_web/q mem/dcache/tag_cpu_web_reg/Q -type DLAT DLAT
add mapped point mem/dcache/cpu_resp_data[0]/q mem/dcache/cpu_resp_data_reg[0]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[14]/q mem/dcache/cpu_resp_data_reg[14]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[30]/q mem/dcache/cpu_resp_data_reg[30]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[31]/q mem/dcache/cpu_resp_data_reg[31]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[2]/q mem/dcache/cpu_resp_data_reg[2]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[15]/q mem/dcache/cpu_resp_data_reg[15]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[6]/q mem/dcache/cpu_resp_data_reg[6]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[7]/q mem/dcache/cpu_resp_data_reg[7]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[16]/q mem/dcache/cpu_resp_data_reg[16]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[25]/q mem/dcache/cpu_resp_data_reg[25]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[17]/q mem/dcache/cpu_resp_data_reg[17]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[8]/q mem/dcache/cpu_resp_data_reg[8]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[18]/q mem/dcache/cpu_resp_data_reg[18]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[19]/q mem/dcache/cpu_resp_data_reg[19]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[20]/q mem/dcache/cpu_resp_data_reg[20]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[3]/q mem/dcache/cpu_resp_data_reg[3]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[9]/q mem/dcache/cpu_resp_data_reg[9]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[24]/q mem/dcache/cpu_resp_data_reg[24]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[21]/q mem/dcache/cpu_resp_data_reg[21]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[1]/q mem/dcache/cpu_resp_data_reg[1]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[22]/q mem/dcache/cpu_resp_data_reg[22]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[4]/q mem/dcache/cpu_resp_data_reg[4]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[10]/q mem/dcache/cpu_resp_data_reg[10]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[23]/q mem/dcache/cpu_resp_data_reg[23]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[11]/q mem/dcache/cpu_resp_data_reg[11]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[5]/q mem/dcache/cpu_resp_data_reg[5]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[12]/q mem/dcache/cpu_resp_data_reg[12]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[26]/q mem/dcache/cpu_resp_data_reg[26]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[27]/q mem/dcache/cpu_resp_data_reg[27]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[13]/q mem/dcache/cpu_resp_data_reg[13]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[28]/q mem/dcache/cpu_resp_data_reg[28]/Q -type DFF DFF
add mapped point mem/dcache/cpu_resp_data[29]/q mem/dcache/cpu_resp_data_reg[29]/Q -type DFF DFF
add mapped point mem/dcache/mem_req_valid/q mem/dcache/mem_req_valid_reg/Q -type DLAT DLAT
add mapped point mem/icache/sram_mem_web_0/q mem/icache/sram_mem_web_0_reg/Q -type DLAT DLAT
add mapped point mem/icache/sram_mem_web_1/q mem/icache/sram_mem_web_1_reg/Q -type DLAT DLAT
add mapped point mem/icache/mem_req_valid/q mem/icache/mem_req_valid_reg/Q -type DLAT DLAT
add mapped point mem/icache/tag_cpu_web/q mem/icache/tag_cpu_web_reg/Q -type DLAT DLAT
add mapped point mem/icache/cpu_req_addr_reg[11]/q mem/icache/cpu_req_addr_reg_reg[11]/Q -type DLAT DLAT
add mapped point mem/icache/memory_rw_ctr[1]/q mem/icache/memory_rw_ctr_reg[1]296/QN -type DFF DFF
add mapped point mem/icache/state[1]/q mem/icache/state_reg[1]/QN -type DFF DFF
add mapped point mem/icache/memory_rw_ctr[0]/q mem/icache/memory_rw_ctr_reg[0]295/QN -type DFF DFF
add mapped point mem/icache/state[0]/q mem/icache/state_reg[0]/QN -type DFF DFF
add mapped point mem/icache/cpu_req_ready/q mem/icache/cpu_req_ready_reg304/Q -type DLAT DLAT



//Black Boxes
add mapped point mem/dcache/CACHE_DATA_BANK_0_0 mem/dcache/CACHE_DATA_BANK_0_0 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_0_1 mem/dcache/CACHE_DATA_BANK_0_1 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_0_2 mem/dcache/CACHE_DATA_BANK_0_2 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_0_3 mem/dcache/CACHE_DATA_BANK_0_3 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_1_0 mem/dcache/CACHE_DATA_BANK_1_0 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_1_1 mem/dcache/CACHE_DATA_BANK_1_1 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_1_2 mem/dcache/CACHE_DATA_BANK_1_2 -type BBOX BBOX
add mapped point mem/dcache/CACHE_DATA_BANK_1_3 mem/dcache/CACHE_DATA_BANK_1_3 -type BBOX BBOX
add mapped point mem/dcache/TAGS mem/dcache/TAGS -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_0_0 mem/icache/CACHE_DATA_BANK_0_0 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_0_1 mem/icache/CACHE_DATA_BANK_0_1 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_0_2 mem/icache/CACHE_DATA_BANK_0_2 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_0_3 mem/icache/CACHE_DATA_BANK_0_3 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_1_0 mem/icache/CACHE_DATA_BANK_1_0 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_1_1 mem/icache/CACHE_DATA_BANK_1_1 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_1_2 mem/icache/CACHE_DATA_BANK_1_2 -type BBOX BBOX
add mapped point mem/icache/CACHE_DATA_BANK_1_3 mem/icache/CACHE_DATA_BANK_1_3 -type BBOX BBOX
add mapped point mem/icache/TAGS mem/icache/TAGS -type BBOX BBOX



//Empty Modules as Blackboxes
